_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 55
                - 86
                - 105
            "2":
                - 55
                - 86
                - 92
                - 95
                - 105
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.0
            "5": 0.19.4
            "8":
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
chunk_overlap:
    value: 200
chunk_size:
    value: 5000
docs_dir:
    value: C:\dev\EE569\Assignment2-LLM\MYLLM\docs_sample
prompt_file:
    value: C:\dev\EE569\Assignment2-LLM\prompts.json
vector_store:
    value: ./vector_store
wandb_project:
    value: llmapps
